server:
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ENC(42WYIfUytCVQfEbhbpYW0DglBLb9py1sBvOJ8tMFCcwTYRetUcDQZjRxnfHOpR0laALK7BpiAxc3rC24QdD4fwP31b/uQxDb7ug+kwOWzf+gihjznRgToCPxNMY2tVthqwEvrqN9CtU/Tl7YlwBQjs4avOtYdlNSv/zGFYguLyU2LHg+4T6WQbCLX4Zvff4agNM9TQjpLCw=)
    username: ENC(KECJYP3aLTAaS/1ffwfn2Q==)
    password: ENC(dH70a8PAfeYkwJ/fS9oTCyQ7nIM9QfYhlVqbVF+T/0A=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ENC(+mNfUF8iXbnTe2oQ58Z2WA==)
      port: 6379
      password: ENC(fFn96KY60L7dV8VvoBEASYnsAHjA4BPN)

cloud:
  aws:
    credentials:
      access-key: ENC(+l4c0mplvKPCS0nvLyzdMy/wrlhgrhnnZQ9C7DOBJJM=)
      secret-key: ENC(YA+/sMt2h4nNy/sNpp1ZOXeQp1XN5+8EXMWuyM9XeNebyDgr3ZubBtKTTGLDs7k/byX5rC5RIX8=)
    s3:
      bucket: ENC(lb9nVofzWL0UXlY8FD9X0Nj8wy5lj2P7)
    region:
      static: ap-northeast-2

# 프론트엔드 URL (OAuth 콜백 리다이렉트용)
app:
  frontend-url: https://hcm-red.vercel.app

# 로깅 설정
logging:
  level:
    root: WARN
    com.behcm: INFO