jwt:
  secret: ENC(tn+jL13JOXRED68uywlMmd+49arLLpw/M7u4MAo0lLi1yKPJtiLK4mQOLmbUpXjiu6Y3QDWgEOoiJxfNQRECIrP3mz5KNQglwCHMQgcymI2fcV2KQYpY1hqTVVJJ8EQgELwRJaDX9RETvU5a/tsCk38jwNm8O4XXAqg9mhOflbQ=)
  access-token-expiration: 86400000 # 24시간(ms)
  refresh-token-expiration: 604800000 # 7일(ms)

korea-investment:
  api:
    base-url: https://openapi.koreainvestment.com:9443
    app-key: ENC(y7XaVJ1gyGoyFtaelgjYbxdrQehRhYj104C/VjJ1PfiJIirbc6EPnLAYQ/wBaEY9)
    app-secret: ENC(xCrQHEDBbQWKAcXLFJFEmUJSqfL3b7kbRIkXGjoVv7ep6g4FM6jMzuxs+r1rRq+p7LLIWL9dLzetT1e59NnLkEPBrPfVQ549yc9ErgNEVCEmpoC+R4F9QWpctjYHWVBBa7YdJRb5ZllF/KNBVQ9jvEjYIiOb8NHLRHvWCz6W7UzKAc2YZ8nwQ2Cgqf0Y20+XsHpAHbXYPO1LetE4VlTn1irI19uBjrPmQpac42c/jqaVL28GqCmySwPdYGQXPFW9)
    account-number: ENC(QgDakrUvj3FEgL7gY1J2ELWdpn1NIc9Z)
    account-product-code: ENC(qIjntUzjQyi9vsr9F08ACA==)
