spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(w43r+JK4IxkLaz67OZbo9/Sw9jvs0dLStb+GUsc+yZdWLeFiuMEvbAishy3kMxWHaqOnbpCVxNg/Yx9grYShknzUlNYOYJ/IUC8BzTPXUX2XkUXmdvXykvRP+VtD584xFLL+Vb4LrpY2xb/ja0gtnfhqG5w5YhudkA3+6b5eO1a3e6SBXSiALZEYAQHHLUk4VkH2+G1pPB1qfKqODtFxFA==)
    username: ENC(lVSrqCpmTW5Z7LsDVhoNIQ==)
    password: ENC(xGO3ZGAnd1V6vd8YK0vE621ooscZjt+EGrK+v183NKU=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ENC(biGY1NB/OG+9fMjwd9xydQ==)
      port: 6379
      password: ENC(f/q6GpGysypGkQk/Mswp9J3L2U3SLMwp)

cloud:
  aws:
    credentials:
      access-key: ENC(+l4c0mplvKPCS0nvLyzdMy/wrlhgrhnnZQ9C7DOBJJM=)
      secret-key: ENC(YA+/sMt2h4nNy/sNpp1ZOXeQp1XN5+8EXMWuyM9XeNebyDgr3ZubBtKTTGLDs7k/byX5rC5RIX8=)
    s3:
      bucket: ENC(lb9nVofzWL0UXlY8FD9X0Nj8wy5lj2P7)
    region:
      static: ap-northeast-2

# 로깅 설정
logging:
  level:
    root: INFO
    com.behcm: INFO